sonar.projectKey=arseniyfaryna_DefenseInformLabs
sonar.organization=arseniyfaryna

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11.9
sonar.python.coverage.reportPaths=coverage.xml